apiVersion: v1
kind: Namespace
metadata:
  name: myapp

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      annotations:
        container.apparmor.security.beta.kubernetes.io/redisname: unconfined
      labels:
        app: myapp
    spec:
      containers:
      - name: nginxname
        image: nginx
      - name: redisname
        image: redis
