name: check_commit_compile

on: [pull_request]

jobs:
  check_commit_compile:
    name: Check if kubearmor compiles for every commit
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Configure git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "github-actions@users.noreply.github.com"
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18     
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
          
      - name: Check if build works for every commit
        uses: actions/checkout@v2
        with:
          # checkout full tree
          fetch-depth: 0
          run: |
            for commit in $(git rev-list ${{ github.event.before}}..${{ github.sha}}); do
                git checkout $commit
                cd KubeArmor
                make build
                if [ $? -eq 0 ]; then
                  echo "commit $commit compiled"
                else
                  echo "failed to compile $commit"
                fi
            done