name: ci-test

on:
  push:
    branches: [main]
    paths: 
    - 'KubeArmor/**'
    - 'tests/**'
    - 'protobuf/**'
    - '.github/workflows/ci-test.yml'
  pull_request:
    branches: [main]
    paths: 
    - 'KubeArmor/**'
    - 'tests/**'
    - 'protobuf/**'
    - '.github/workflows/ci-test.yml'

jobs:
  build:
    name: Auto-testing Framework / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, ubuntu-18.04]
    steps:
      - name: Kernel version
        run: uname -r

      - name: Check Docker Version
        run: docker --version

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Build bcc
        run: |
          set -x
          sudo apt-get update
          sudo apt-get -y install build-essential cmake bison flex git python3 python3-pip clang-9 libllvm9 llvm-9-dev libclang-9-dev zlib1g-dev libelf-dev libedit-dev libfl-dev
          pushd /tmp
          # fetch latest bcc release
          git clone --branch v0.24.0 --depth 1 https://github.com/iovisor/bcc.git
          mkdir -p bcc/build; cd bcc/build
          sudo ln -s /usr/lib/llvm-9 /usr/local/llvm
          cmake .. -DPYTHON_CMD=python3 -DCMAKE_INSTALL_PREFIX=/usr
          make -j$(nproc)
          sudo make install
          popd

      - name: Setup Enviroment
        run: |
          ./contribution/k3s/install_k3s.sh

      - name: Run kubectl proxy
        run: kubectl proxy &

      - name: Install annotation controller
        run: |
          sudo apt install -y docker-ce
          sudo chmod 666 /var/run/docker.sock
          pushd $(pwd)
          kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.8.0/cert-manager.yaml
          cd pkg/KubeArmorAnnotation
          make docker-build  IMG=webhook
          make deploy IMG=webhook
          sleep 5
          kubectl get -A
          popd
      - name: Test KubeArmor
        run: ./tests/test-scenarios-github.sh
        timeout-minutes: 15

      - name: Archive log artifacts
        if: ${{ failure() }}
        uses: actions/upload-artifact@v2
        with:
          name: kubearmor.logs
          path: |
            /tmp/kubearmor.test
            /tmp/kubearmor.log
            /tmp/kubearmor.msg

      - name: Check Results
        if: ${{ always() }}
        run: cat /tmp/kubearmor.test

      - name: Measure Code Coverage
        if: ${{ always() }}
        run: |
          go get github.com/modocache/gover
          gover    
          go tool cover -func=gover.coverprofile
        working-directory: KubeArmor
        env:
          GOPATH: /home/runner/go

      - uses: codecov/codecov-action@v2
        if: ${{ always() }}
        with:
          files: ./KubeArmor/gover.coverprofile
